[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/offerings"
  to = "/pages/offerings.html"
  status = 200

[[redirects]]
  from = "/detail"
  to = "/pages/detail.html"
  status = 200
